export const ROLES = {
  ADMIN: 'ADMIN',
  INVESTOR: 'INVESTOR',
  SELLER: 'SELLER',
  COMPLIANCE: 'COMPLIANCE',
  OPS: 'OPS',
} as const;

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  OPEN: 'OPEN',
  FILLED: 'FILLED',
  PARTIALLY_FILLED: 'PARTIALLY_FILLED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
} as const;

export const DEAL_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ALLOCATING: 'ALLOCATING',
  DOCS_PENDING: 'DOCS_PENDING',
  FUNDING: 'FUNDING',
  SETTLING: 'SETTLING',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
} as const;

export const KYC_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
} as const;
